lista_distribuciones<-matrix(c("Beta","beta",
                               "Binomial","binom",
                               "Cauchy","cauchy",
                               "Chi2","chisq",
                               "Exponencial","exp",
                               "F","f",
                               "Gamma","gamma",
                               "Geometrica","geom",
                               "Hipergeometrica","hyper",
                               "Lognormal","lnorm",
                               "Multinomial","multinom",
                               "Binomial negativa","nbinom",
                               "Normal","norm",
                               "Poisson","pois",
                               "t-student","t",
                               "Uniforme","unif",
                               "Weibull","weibull"),byrow = T,ncol=2)
